### ISSUE TITLE
dot-consultthat

### ISSUE THREAD

**Issue by rmflight** [stephdesilva/consultthat#4]
As discussed on the pull request, I am working on implementing having a `.consultthat` file that contains the actual directory name.

* This will be the first try to getting the directory structure, and then fall-back to `project_documents`, does that seem reasonable?

* While making this change, I also thought about adding the option to **not create a package**, but rather just create the directory, without all the package stuff, if desired. This would be a parameter of `createProject`, so the function call would look like: `createProject(..., use_package = FALSE)`, with `TRUE` being the default.

**Comment by stephstammel** [comment]
I think that's a brilliant move - one of the twitter feedback comment was that the automatic package launch/requirement was a drawback. I think this matters for those early to using R/modern workflows, allowing them to be using a project instead without the extra infrastructure.

In that sense, possible use_package = FALSE as default would be most user friendly?
